[package]
name = "json_dictionary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "=1.0"
serde = { version = "1.0", features = ["derive"] }
difflib = "0.4.0"
fltk = "1.3.9"